title: SatMapKit
description: Tools for satellite altimetry research
url: "https://satmapkit.github.io"
baseurl: ""
timezone: America/Los_Angeles
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - tools
  - output
  - .bundle
